### ISSUE TITLE
Schedule Post is not working.

### ISSUE THREAD

**Issue by GauriBansal** [reach2gauri/Kheech#12]
When I submit the button on the schedule form, it does not take me to Post method on the controller. It simply refresh the same form.

**Comment by pscholtes** [comment]
The POST is looking for a `ScheduleViewModel` but it doesn't look like you're using that for the DATA.

**Comment by GauriBansal** [comment]
Fixed it. refer Kheech/Kheech/Kheech.Web/Views/KheechEvent/Schedule.cshtml
