### ISSUE TITLE
My Toastr messages are not working. 

### ISSUE THREAD

**Issue by GauriBansal** [reach2gauri/Kheech#26]
Hey Phil, 

Could you please look into my Toastr message problem? I have added a Ajax call for deleting comments in KheechEvent -> details view. I have added the bundleConfig as well as nuget package. Am I missing a step here?

**Comment by pscholtes** [comment]
@GauriBansal check to make sure that the toastr library on the page. When I run this command in the Chrome console window, it doesn't know what toastr is:

![image](https://user-images.githubusercontent.com/2772725/42177365-1fdd56c0-7df2-11e8-93e3-bb3ab982852e.png)

This is probably why it isn't working. I see you have toastr added via NuGet and you have it included in a bundle called "vendor":

`bundles.Add(new ScriptBundle("~/bundles/vendor").Include("~/Scripts/toastr.js"));`

But where are you including that JS on the page? You need to add it to your markup

`@Scripts.Render("~/bundles/vendor")`

Which should resolve your issue:

![image](https://user-images.githubusercontent.com/2772725/42177438-5d298c92-7df2-11e8-9025-ccdb80a256c5.png)
