### ISSUE TITLE
SendGrid email send is breaking

### ISSUE THREAD

**Issue by GauriBansal** [reach2gauri/Kheech#27]
Hey Phil,

I created a new send grd account and everything is set there. I copied your code. However, the inviteFriendPost (friends -> index) is not working. I am getting error "**Unable to read data from the transport connection: The connection was closed**."

Could you please have a look there?

**Comment by pscholtes** [comment]
@GauriBansal where is your API key? Looking at this code, which creates and instance of the SendGridEmailClient object, you are passing 1 string parameter:

`var sendGridClient = new SendGridEmailClient("SendGridApiKey");`

Then looking in the constructor code, you're using that input parameter as follows:

```
private readonly SendGridClient _sendGridApi;

public SendGridEmailClient(string apiKey)
{
   _sendGridApi = new SendGridClient(apiKey);
}
```

What looks wrong here?
