### ISSUE TITLE
Kheech Home Page - after login

### ISSUE THREAD

**Issue by GauriBansal** [reach2gauri/Kheech#7]
Once user logins at the website, this page would be loaded.

**Comment by GauriBansal** [comment]
This page does not show my ViewData. I have a if-else statement on my view page.

**Comment by pscholtes** [comment]
I see ViewData on KeechEvent/Index, but no ViewData code on the corresponding Controller method. Look closely there.

**Comment by GauriBansal** [comment]
Fixed it.
